# Generated by Django 4.0.6 on 2022-08-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('program_name', models.CharField(max_length=100)),
                ('kid_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('kid_age', models.CharField(max_length=10)),
                ('mother_name', models.CharField(max_length=45)),
                ('father_name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=45)),
                ('address', models.TextField()),
                ('kid_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('school_name', models.CharField(max_length=40)),
                ('transaction_number', models.CharField(max_length=40)),
            ],
        ),
    ]
