# Generated by Django 4.0.6 on 2022-08-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetapp', '0002_admissionform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('pic', models.FileField(default='', upload_to='planetapp/picture')),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
